// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myovnlxheufjmmgehczu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15b3ZubHhoZXVmam1tZ2VoY3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMDAxOTYsImV4cCI6MjA3MzU3NjE5Nn0.rM3LwoAjECC5UN3mfUzALfLqQIjgPNNN4O-gdgf7cuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});